version: "3"

services:
  mysql-wanted:
    container_name: mysql-wanted
    image: mysql:8.0.22
    environment:
      - MYSQL_DATABASE=wanted
      - MYSQL_ROOT_PASSWORD=mysqlpw
    ports:
      - "3306:3306"
    networks:
      - wanted-net
    volumes:
      - ./volume/mysql-wanted:/var/lib/mysql
      - ./initdb.d:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10

  springboot-wanted:
    container_name: springboot-wanted
    build:
      context: .
      dockerfile: Dockerfile
    image: springboot-wanted:0.0.1
    ports:
      - "80:80"
    networks:
      - wanted-net
    depends_on:
      mysql-wanted:
        condition: service_healthy
    volumes:
      - ./volume/springboot-wanted:/var/log/spring

networks:
  wanted-net:
    driver: bridge